import {
  MessageCircle,
  Hand,
  Brain,
  GraduationCap,
  Puzzle,
  Blocks,
  Activity,
  Waves,
  Baby,
  BookOpen,
  Accessibility,
  HeartHandshake,
  Users,
  UserRound,
  Sparkles,
  Users2,
  Video,
  ClipboardList,
} from "lucide-react";
import type { Service } from "@/types";

/**
 * Source of truth for all therapy services. Each entry renders a full detail
 * page via app/(marketing)/services/[slug]/page.tsx.
 */
export const services: Service[] = [
  {
    slug: "speech-therapy",
    title: "Speech Therapy",
    shortDescription:
      "Helping children communicate clearly through language, articulation, fluency and feeding therapy.",
    icon: MessageCircle,
    heroTagline: "Give your child the confidence to be heard.",
    ageRange: "18 months – 16 years",
    featured: true,
    overview: [
      "Speech and language therapy supports children who have difficulty understanding language, expressing themselves, pronouncing sounds, stammering, or feeding safely. Our certified speech-language pathologists use play-based, evidence-driven techniques tailored to each child.",
      "Whether your child is a late talker, has unclear speech, or struggles with social communication, we build a personalised plan that turns everyday moments into meaningful communication practice — at the clinic and at home.",
    ],
    symptoms: [
      "Limited vocabulary or not talking by expected age",
      "Speech that is hard for others to understand",
      "Stammering or repeating sounds and words",
      "Difficulty following instructions or answering questions",
      "Trouble with chewing, swallowing or fussy eating",
      "Frustration when trying to communicate",
    ],
    benefits: [
      "Clearer, more confident speech",
      "Stronger vocabulary and sentence-building",
      "Better listening and comprehension",
      "Improved social communication and turn-taking",
      "Safer, more comfortable feeding",
      "Reduced frustration and behavioural outbursts",
    ],
    process: [
      { title: "Speech & Language Assessment", description: "A standardised evaluation of receptive and expressive language, articulation and oral-motor skills." },
      { title: "Goal Setting", description: "We agree clear, measurable goals with you based on your child's needs and priorities." },
      { title: "Therapy Sessions", description: "Fun, structured one-on-one sessions using games, stories and real-life practice." },
      { title: "Home Program & Review", description: "Simple home activities plus regular progress reviews to keep momentum going." },
    ],
    duration: "Typically 30–45 minute sessions, 1–2 times per week, reviewed every 8–12 weeks.",
    faqs: [
      { question: "At what age should I be concerned about speech?", answer: "If your child isn't using single words by 18 months or two-word phrases by two years, an assessment is worthwhile. Earlier support usually means faster progress." },
      { question: "How long will therapy take?", answer: "It varies with each child. Some meet their goals in a few months; others benefit from longer-term support. We review progress every 8–12 weeks and adjust the plan." },
      { question: "Can I be involved in sessions?", answer: "Absolutely. Parent involvement is one of the biggest predictors of success, and we coach you on how to support communication at home." },
    ],
  },
  {
    slug: "occupational-therapy",
    title: "Occupational Therapy",
    shortDescription:
      "Building fine-motor, sensory and daily-living skills so children can participate fully in everyday life.",
    icon: Hand,
    heroTagline: "Empowering independence, one skill at a time.",
    ageRange: "2 – 16 years",
    featured: true,
    overview: [
      "Occupational therapy helps children develop the skills they need for daily activities — from holding a pencil and using cutlery to dressing, playing and self-regulation. Our occupational therapists focus on the 'occupations' of childhood: learning, playing and growing.",
      "Using purposeful, motivating activities, we strengthen fine and gross motor control, hand-eye coordination, sensory processing and attention, so your child can thrive at home, in school and with friends.",
    ],
    symptoms: [
      "Awkward pencil grip or messy handwriting",
      "Difficulty with buttons, zips or shoelaces",
      "Clumsiness or poor coordination",
      "Over- or under-reacting to sounds, textures or movement",
      "Short attention span and difficulty sitting still",
      "Avoiding messy play or certain foods",
    ],
    benefits: [
      "Improved handwriting and fine-motor control",
      "Greater independence in self-care",
      "Better balance, coordination and posture",
      "Calmer responses to sensory input",
      "Increased focus and task completion",
      "More confident participation in play and school",
    ],
    process: [
      { title: "Developmental Assessment", description: "We evaluate motor, sensory and self-care skills against age expectations." },
      { title: "Individualised Plan", description: "A tailored plan targeting the skills that matter most for your child." },
      { title: "Play-Based Therapy", description: "Engaging sessions using climbing, crafts, games and sensory activities." },
      { title: "Home & School Strategies", description: "Practical adaptations and exercises to reinforce gains everywhere." },
    ],
    duration: "45-minute sessions, 1–2 times per week, with reviews every 10–12 weeks.",
    faqs: [
      { question: "What is sensory processing?", answer: "It's how the brain interprets information from the senses. Some children are over- or under-sensitive, which can affect behaviour, focus and daily activities. OT helps them regulate." },
      { question: "Will OT help with handwriting?", answer: "Yes — handwriting relies on fine-motor control, posture and visual-motor skills, all of which occupational therapy directly targets." },
      { question: "Is OT only for children with a diagnosis?", answer: "No. Many children benefit from OT for coordination, attention or self-care challenges without any formal diagnosis." },
    ],
  },
  {
    slug: "behavior-therapy",
    title: "Behaviour Therapy",
    shortDescription:
      "Positive, structured strategies that reduce challenging behaviour and build emotional regulation.",
    icon: Brain,
    heroTagline: "Turning challenging moments into growth.",
    ageRange: "2 – 16 years",
    overview: [
      "Behaviour therapy helps children replace challenging behaviours with positive, functional ones. We identify what a behaviour is communicating and teach new skills for coping, communicating and self-regulating.",
      "Using compassionate, evidence-based techniques and consistent routines, our therapists partner with families to create supportive environments where children feel understood and can flourish.",
    ],
    symptoms: [
      "Frequent tantrums or meltdowns",
      "Aggression, biting or hitting",
      "Difficulty following rules or routines",
      "Trouble managing big emotions",
      "Non-compliance or defiance",
      "Difficulty transitioning between activities",
    ],
    benefits: [
      "Fewer and shorter behavioural outbursts",
      "Better emotional self-regulation",
      "Improved cooperation and routines",
      "Stronger communication of needs",
      "Calmer home and classroom environment",
      "Confident, consistent parenting strategies",
    ],
    process: [
      { title: "Behaviour Assessment", description: "We observe and analyse behaviours to understand their triggers and functions." },
      { title: "Support Plan", description: "A positive behaviour support plan with clear, practical strategies." },
      { title: "Skill Building", description: "Teaching replacement skills — communication, coping and self-regulation." },
      { title: "Parent Coaching & Review", description: "Ongoing coaching so strategies work consistently at home and school." },
    ],
    duration: "45–60 minute sessions, weekly, with regular parent-coaching check-ins.",
    faqs: [
      { question: "Is behaviour therapy the same as punishment?", answer: "No. Modern behaviour therapy is positive and skill-focused — we teach children better ways to communicate and cope, rather than punishing them." },
      { question: "How involved do parents need to be?", answer: "Very. Consistency between clinic and home is key, so we coach parents throughout the program." },
      { question: "Can it help siblings too?", answer: "The routines and strategies you learn often benefit the whole family and can be applied with siblings." },
    ],
  },
  {
    slug: "special-education",
    title: "Special Education",
    shortDescription:
      "Individualised learning plans that help children master reading, writing, maths and concepts at their own pace.",
    icon: GraduationCap,
    heroTagline: "Learning designed around your child.",
    ageRange: "3 – 16 years",
    featured: true,
    overview: [
      "Our special educators design individualised education programs (IEPs) for children who learn differently. We break skills into achievable steps and use multi-sensory teaching to make learning accessible and enjoyable.",
      "From pre-academic readiness to reading, writing and numeracy, we meet each child where they are and build the foundations for lifelong learning and school success.",
    ],
    symptoms: [
      "Struggling to keep up with class work",
      "Difficulty reading, writing or with numbers",
      "Poor memory or concept retention",
      "Short attention span during learning",
      "Low confidence around academics",
      "Needs repeated instructions to understand",
    ],
    benefits: [
      "Personalised, achievable learning goals",
      "Stronger literacy and numeracy skills",
      "Improved attention and study habits",
      "Multi-sensory strategies that stick",
      "Greater academic confidence",
      "Smoother inclusion in mainstream school",
    ],
    process: [
      { title: "Educational Assessment", description: "We identify current levels, strengths and learning gaps." },
      { title: "Individualised Education Plan", description: "A step-by-step IEP with measurable academic goals." },
      { title: "One-on-One Teaching", description: "Multi-sensory sessions tailored to how your child learns best." },
      { title: "Progress Reviews", description: "Regular reviews with parents and, where helpful, the child's school." },
    ],
    duration: "45-minute sessions, 2–3 times per week, with termly IEP reviews.",
    faqs: [
      { question: "Do you coordinate with my child's school?", answer: "Yes, with your consent we collaborate with teachers to align goals and support inclusion." },
      { question: "Is this only for children with learning disabilities?", answer: "No — we support any child who benefits from individualised, structured teaching, including school readiness." },
      { question: "What is an IEP?", answer: "An Individualised Education Plan is a tailored roadmap of goals and strategies specific to your child's needs." },
    ],
  },
  {
    slug: "autism-therapy",
    title: "Autism Therapy",
    shortDescription:
      "Comprehensive, compassionate support for children on the autism spectrum across communication, behaviour and daily skills.",
    icon: Puzzle,
    heroTagline: "Understanding, supporting and celebrating every child.",
    ageRange: "18 months – 16 years",
    featured: true,
    overview: [
      "Our autism program brings together speech therapy, occupational therapy, behaviour support and special education into one coordinated plan. We focus on communication, social skills, sensory needs and independence — always respecting each child's unique strengths.",
      "Early, intensive and individualised intervention makes a lasting difference. Our multidisciplinary team works closely with families to build skills that generalise to home, school and the community.",
    ],
    symptoms: [
      "Delayed speech or limited communication",
      "Limited eye contact or social interaction",
      "Repetitive movements or intense interests",
      "Strong need for routine and sameness",
      "Sensory sensitivities",
      "Difficulty with changes and transitions",
    ],
    benefits: [
      "Improved communication and social connection",
      "Better emotional and sensory regulation",
      "Greater independence in daily routines",
      "Reduced anxiety around change",
      "A coordinated, multidisciplinary plan",
      "Empowered, supported parents",
    ],
    process: [
      { title: "Comprehensive Assessment", description: "A multidisciplinary evaluation of communication, behaviour, sensory and learning needs." },
      { title: "Individualised Program", description: "A coordinated plan across therapies tailored to your child." },
      { title: "Intensive Intervention", description: "Regular, structured sessions building communication and life skills." },
      { title: "Family Partnership", description: "Parent training and reviews to sustain progress everywhere." },
    ],
    duration: "Plans are individualised; many children benefit from several sessions per week across disciplines.",
    faqs: [
      { question: "How early can therapy begin?", answer: "As early as concerns arise — often before age two. Early intervention is strongly linked to better outcomes." },
      { question: "Which therapies does the program include?", answer: "Depending on needs: speech therapy, occupational therapy, ABA/behaviour support, special education and parent counselling — coordinated by one team." },
      { question: "Do you provide a diagnosis?", answer: "Our psychologists offer autism assessments; therapy can also begin based on developmental needs while assessment is underway." },
    ],
  },
  {
    slug: "aba-therapy",
    title: "ABA Therapy",
    shortDescription:
      "Applied Behaviour Analysis programs that build communication, social and daily-living skills through positive reinforcement.",
    icon: Blocks,
    heroTagline: "Evidence-based skill building that lasts.",
    ageRange: "2 – 12 years",
    overview: [
      "Applied Behaviour Analysis (ABA) is a well-researched approach that teaches new skills and reduces barriers to learning by breaking them into small, teachable steps and reinforcing progress positively.",
      "Our programs are naturalistic, play-based and individualised — never one-size-fits-all. We measure progress closely and adjust continuously so your child keeps moving forward.",
    ],
    symptoms: [
      "Difficulty learning new skills",
      "Limited communication",
      "Challenging behaviours that interfere with learning",
      "Trouble with attention and following instructions",
      "Difficulty with social interaction",
      "Struggles with daily-living tasks",
    ],
    benefits: [
      "Structured, measurable skill development",
      "Improved communication and requesting",
      "Reduced challenging behaviour",
      "Better attention and learning readiness",
      "Skills that generalise across settings",
      "Data-driven, transparent progress",
    ],
    process: [
      { title: "Assessment & Baseline", description: "We assess current skills and set individualised, prioritised targets." },
      { title: "Program Design", description: "A tailored ABA plan with clear goals and reinforcement strategies." },
      { title: "Therapy & Data", description: "Consistent sessions with continuous data collection on progress." },
      { title: "Review & Parent Training", description: "Regular analysis of data and coaching for carry-over at home." },
    ],
    duration: "Individualised — from focused programs to more intensive schedules based on need.",
    faqs: [
      { question: "Is ABA play-based?", answer: "Yes. Modern ABA uses naturalistic, child-led play to make learning motivating and meaningful." },
      { question: "How is progress measured?", answer: "We collect data every session and review it regularly, so decisions are transparent and evidence-based." },
      { question: "Is ABA only for autism?", answer: "ABA principles help many children, though it's most commonly used to support children with autism." },
    ],
  },
  {
    slug: "adhd-management",
    title: "ADHD Management",
    shortDescription:
      "Practical strategies and skills that help children with attention and hyperactivity thrive at home and school.",
    icon: Activity,
    heroTagline: "Focus, calm and confidence — within reach.",
    ageRange: "4 – 16 years",
    overview: [
      "We help children with ADHD strengthen attention, impulse control, organisation and emotional regulation using structured, strengths-based strategies. Our approach supports the whole child — and the family and school around them.",
      "Through skill-building, behavioural strategies and parent coaching, we reduce daily friction and help children channel their energy and creativity productively.",
    ],
    symptoms: [
      "Difficulty sustaining attention",
      "Easily distracted or forgetful",
      "Fidgeting and constant movement",
      "Acting without thinking",
      "Trouble organising tasks",
      "Difficulty waiting or taking turns",
    ],
    benefits: [
      "Improved attention and task completion",
      "Better impulse control",
      "Stronger organisation and routines",
      "Calmer emotional responses",
      "Reduced homework and morning battles",
      "Confident, consistent parenting tools",
    ],
    process: [
      { title: "Assessment", description: "We understand your child's attention profile, strengths and challenges." },
      { title: "Strategy Plan", description: "Personalised strategies for focus, organisation and regulation." },
      { title: "Skill Coaching", description: "Sessions that build executive-function and self-management skills." },
      { title: "Parent & School Support", description: "Practical systems and coaching for home and classroom." },
    ],
    duration: "45-minute sessions, weekly, with parent-coaching check-ins.",
    faqs: [
      { question: "Do you prescribe medication?", answer: "We focus on behavioural and skills-based support and can coordinate with your paediatrician if medication is being considered." },
      { question: "Can strategies help at school?", answer: "Yes — with your consent we share practical classroom strategies with teachers." },
      { question: "Will my child grow out of ADHD?", answer: "ADHD often continues, but the right strategies help children manage it well and succeed throughout life." },
    ],
  },
  {
    slug: "sensory-integration",
    title: "Sensory Integration Therapy",
    shortDescription:
      "Specialised therapy that helps children process and respond to sensory information for calmer, focused days.",
    icon: Waves,
    heroTagline: "Helping the senses make sense.",
    ageRange: "2 – 12 years",
    overview: [
      "Sensory integration therapy helps children who are over- or under-responsive to sensory input — sounds, textures, movement or light — regulate their responses so they can focus, play and learn comfortably.",
      "In our sensory gym, therapists use carefully graded, playful activities that build the brain's ability to organise sensory information, improving attention, coordination and self-regulation.",
    ],
    symptoms: [
      "Distress at loud sounds or bright lights",
      "Avoiding or craving messy textures",
      "Constant movement or seeking deep pressure",
      "Poor balance and coordination",
      "Difficulty calming down",
      "Fussy eating linked to textures",
    ],
    benefits: [
      "Calmer responses to sensory input",
      "Improved focus and participation",
      "Better coordination and body awareness",
      "Reduced anxiety and meltdowns",
      "Greater comfort with daily activities",
      "Improved sleep and self-regulation",
    ],
    process: [
      { title: "Sensory Assessment", description: "We profile how your child processes each sensory system." },
      { title: "Sensory Plan", description: "A tailored 'sensory diet' and therapy plan for regulation." },
      { title: "Sensory-Gym Sessions", description: "Playful, graded activities that build sensory processing." },
      { title: "Home Strategies", description: "Simple sensory tools and routines to use every day." },
    ],
    duration: "45-minute sessions, 1–2 times per week, reviewed every 10–12 weeks.",
    faqs: [
      { question: "What is a 'sensory diet'?", answer: "It's a personalised set of sensory activities scheduled through the day to help your child stay regulated and focused." },
      { question: "Is this the same as occupational therapy?", answer: "Sensory integration is a specialised area within occupational therapy, delivered by trained OTs." },
      { question: "How soon will we see change?", answer: "Many families notice calmer responses within a few weeks, with continued gains over time." },
    ],
  },
  {
    slug: "developmental-delay",
    title: "Developmental Delay Support",
    shortDescription:
      "Milestone-focused therapy that helps children catch up across motor, language, social and cognitive skills.",
    icon: Baby,
    heroTagline: "Every milestone matters.",
    ageRange: "0 – 6 years",
    overview: [
      "When a child is slower to reach milestones like sitting, walking, talking or playing, targeted early support can make a significant difference. We identify delays and build the underlying skills through play and family coaching.",
      "Our multidisciplinary team addresses motor, communication, social and cognitive development together, giving your child the best foundation for future learning.",
    ],
    symptoms: [
      "Late sitting, crawling or walking",
      "Delayed babbling or first words",
      "Limited play or social interest",
      "Difficulty with problem-solving",
      "Low muscle tone or coordination issues",
      "Not meeting expected milestones",
    ],
    benefits: [
      "Progress toward key milestones",
      "Stronger motor and communication skills",
      "Improved play and social engagement",
      "Early foundations for learning",
      "A coordinated, whole-child plan",
      "Confident, informed parents",
    ],
    process: [
      { title: "Developmental Screening", description: "We assess milestones across all developmental domains." },
      { title: "Early-Support Plan", description: "A play-based plan targeting priority skills." },
      { title: "Therapy Sessions", description: "Engaging sessions that turn play into development." },
      { title: "Family Coaching & Review", description: "We coach you to embed learning into daily routines." },
    ],
    duration: "Individualised; frequency depends on the areas and degree of delay.",
    faqs: [
      { question: "Is a delay the same as a disability?", answer: "No. Many children with delays catch up with timely support; a delay simply means a child needs extra help right now." },
      { question: "How early should we start?", answer: "As soon as you have concerns. The early years are the most responsive time for development." },
      { question: "Which professionals are involved?", answer: "Depending on needs — speech therapists, occupational therapists, special educators and psychologists, working as one team." },
    ],
  },
  {
    slug: "learning-disability",
    title: "Learning Disability Support",
    shortDescription:
      "Targeted remediation for dyslexia, dyscalculia, dysgraphia and other specific learning difficulties.",
    icon: BookOpen,
    heroTagline: "Unlocking the way your child learns best.",
    ageRange: "5 – 16 years",
    overview: [
      "Children with specific learning disabilities are bright and capable but process reading, writing or numbers differently. We use structured, multi-sensory, research-based methods to build these skills and restore confidence.",
      "After a thorough assessment, our special educators design a focused remediation plan and equip your child with strategies and accommodations that support success at school.",
    ],
    symptoms: [
      "Difficulty reading or decoding words",
      "Poor spelling and written expression",
      "Struggles with maths facts and concepts",
      "Reversing letters or numbers",
      "Slow, effortful reading",
      "Underperformance despite effort",
    ],
    benefits: [
      "Improved reading, writing and maths skills",
      "Effective compensatory strategies",
      "Restored academic confidence",
      "Reduced anxiety around schoolwork",
      "Appropriate school accommodations",
      "A clear, individualised plan",
    ],
    process: [
      { title: "Assessment", description: "We pinpoint the specific learning profile and needs." },
      { title: "Remediation Plan", description: "A structured, multi-sensory plan targeting core skills." },
      { title: "One-on-One Teaching", description: "Focused sessions using proven remediation methods." },
      { title: "School Collaboration", description: "We recommend accommodations and liaise with teachers." },
    ],
    duration: "45-minute sessions, 2–3 times per week, with regular progress checks.",
    faqs: [
      { question: "What is dyslexia?", answer: "Dyslexia is a specific difficulty with accurate, fluent reading and spelling, despite good instruction and effort. It responds well to structured intervention." },
      { question: "Will my child always struggle?", answer: "With the right support, children learn effective strategies and make strong progress — many go on to thrive academically." },
      { question: "Do you provide documentation for school?", answer: "Yes. We can provide assessment reports and recommended accommodations to share with your child's school." },
    ],
  },
  {
    slug: "cerebral-palsy-therapy",
    title: "Cerebral Palsy Therapy",
    shortDescription:
      "Motor rehabilitation and functional training that maximise mobility, independence and participation.",
    icon: Accessibility,
    heroTagline: "Maximising ability, enriching life.",
    ageRange: "0 – 16 years",
    overview: [
      "Children with cerebral palsy benefit from coordinated therapy that improves movement, posture, communication and daily function. Our team works to reduce barriers and maximise each child's independence and participation.",
      "We combine occupational therapy, physiotherapy-informed motor work, speech therapy and family training into an individualised plan focused on meaningful, functional goals.",
    ],
    symptoms: [
      "Stiff or floppy muscle tone",
      "Difficulty with movement and posture",
      "Trouble with fine-motor tasks",
      "Feeding or speech difficulties",
      "Delayed motor milestones",
      "Coordination and balance challenges",
    ],
    benefits: [
      "Improved mobility and posture",
      "Greater independence in daily tasks",
      "Better communication and feeding",
      "Reduced discomfort and contracture risk",
      "Functional, meaningful goal progress",
      "Supported, empowered families",
    ],
    process: [
      { title: "Functional Assessment", description: "We evaluate movement, posture, communication and self-care." },
      { title: "Goal-Based Plan", description: "An individualised plan built around functional priorities." },
      { title: "Therapy Sessions", description: "Motor, communication and daily-living focused therapy." },
      { title: "Family & Equipment Support", description: "Home programs and guidance on assistive strategies." },
    ],
    duration: "Individualised and ongoing; frequency depends on goals and needs.",
    faqs: [
      { question: "Can therapy cure cerebral palsy?", answer: "CP is lifelong, but consistent therapy significantly improves function, comfort and independence, and prevents secondary complications." },
      { question: "What therapies are involved?", answer: "Typically occupational therapy, motor and posture work, and speech/feeding therapy — coordinated as one plan." },
      { question: "How do you set goals?", answer: "Around what matters to your family — practical, functional milestones that improve everyday life." },
    ],
  },
  {
    slug: "down-syndrome-support",
    title: "Down Syndrome Support",
    shortDescription:
      "Holistic developmental care that builds communication, motor, learning and life skills at every stage.",
    icon: HeartHandshake,
    heroTagline: "Supporting bright futures at every step.",
    ageRange: "0 – 16 years",
    overview: [
      "Children with Down syndrome thrive with early, consistent and coordinated support. Our multidisciplinary program strengthens communication, motor skills, learning and independence while celebrating each child's personality and strengths.",
      "We partner closely with families across every developmental stage, from early intervention through school years, to help each child reach their fullest potential.",
    ],
    symptoms: [
      "Delayed speech and language",
      "Low muscle tone",
      "Delayed motor milestones",
      "Learning at a different pace",
      "Feeding challenges in infancy",
      "Need for structured, repeated learning",
    ],
    benefits: [
      "Stronger communication skills",
      "Improved motor development",
      "Steady academic and life-skill progress",
      "Greater independence and confidence",
      "A coordinated, whole-child plan",
      "Empowered, well-supported families",
    ],
    process: [
      { title: "Developmental Assessment", description: "We map strengths and needs across all areas." },
      { title: "Individualised Plan", description: "A coordinated plan across relevant therapies." },
      { title: "Therapy & Learning", description: "Engaging sessions building communication, motor and learning skills." },
      { title: "Family Partnership", description: "Coaching and reviews to sustain progress at home." },
    ],
    duration: "Individualised and ongoing across developmental stages.",
    faqs: [
      { question: "When should support begin?", answer: "Early intervention from infancy gives the strongest foundation, but support is valuable at any age." },
      { question: "Which therapies help most?", answer: "A combination of speech, occupational therapy and special education, tailored to your child, works best." },
      { question: "Will my child attend mainstream school?", answer: "Many children with Down syndrome thrive in inclusive settings; we help build the skills and supports that make it possible." },
    ],
  },
  {
    slug: "psychological-counseling",
    title: "Psychological Counseling",
    shortDescription:
      "A safe, supportive space for children and adolescents to work through emotions, anxiety and behaviour.",
    icon: Users,
    heroTagline: "Caring for young minds and hearts.",
    ageRange: "5 – 18 years",
    overview: [
      "Our child and adolescent psychologists provide warm, confidential counselling for children experiencing anxiety, low mood, big emotions, social difficulties or life changes. We help children understand their feelings and build healthy coping skills.",
      "Using age-appropriate, evidence-based approaches such as play therapy and CBT, we support emotional wellbeing and resilience — always in partnership with families.",
    ],
    symptoms: [
      "Persistent worry or anxiety",
      "Sadness, withdrawal or low mood",
      "Frequent emotional outbursts",
      "Difficulty with friendships",
      "Low self-esteem",
      "Struggles after a change or loss",
    ],
    benefits: [
      "Healthy emotional coping skills",
      "Reduced anxiety and worry",
      "Improved mood and resilience",
      "Better friendships and social skills",
      "Stronger self-esteem",
      "A trusted space to be heard",
    ],
    process: [
      { title: "Initial Consultation", description: "We understand your child's world, strengths and concerns." },
      { title: "Supportive Plan", description: "A gentle, age-appropriate counselling approach." },
      { title: "Counselling Sessions", description: "Play- and talk-based sessions that build coping skills." },
      { title: "Family Guidance", description: "Practical guidance so support continues at home." },
    ],
    duration: "45–50 minute sessions, typically weekly or fortnightly.",
    faqs: [
      { question: "Is counselling confidential?", answer: "Yes. We maintain confidentiality appropriate to your child's age, while keeping parents suitably informed and involved." },
      { question: "How do I know if my child needs counselling?", answer: "If emotions or behaviour are affecting daily life, friendships or school, a consultation can help you decide the best support." },
      { question: "Will I be involved?", answer: "Yes — parent guidance is an important part of helping your child feel supported at home." },
    ],
  },
  {
    slug: "parent-counseling",
    title: "Parent Counseling",
    shortDescription:
      "Guidance, coaching and emotional support that empower parents to confidently support their child.",
    icon: UserRound,
    heroTagline: "Because supported parents raise thriving children.",
    ageRange: "Parents & caregivers",
    overview: [
      "Parenting a child with additional needs can be both rewarding and demanding. Our parent counselling offers practical strategies, emotional support and coaching so you feel confident, capable and less alone.",
      "We help you understand your child's needs, manage challenging moments, care for your own wellbeing, and build a supportive, consistent home environment.",
    ],
    symptoms: [
      "Feeling overwhelmed or exhausted",
      "Uncertainty about how to help your child",
      "Difficulty managing behaviour at home",
      "Stress affecting family relationships",
      "Guilt, worry or isolation",
      "Needing consistent strategies",
    ],
    benefits: [
      "Practical, confidence-building strategies",
      "Reduced stress and overwhelm",
      "Better understanding of your child",
      "Consistent routines at home",
      "Improved family wellbeing",
      "A supportive, non-judgmental space",
    ],
    process: [
      { title: "Consultation", description: "We listen and understand your family's situation and goals." },
      { title: "Support Plan", description: "Tailored strategies and coaching priorities." },
      { title: "Coaching Sessions", description: "Practical, supportive sessions you can apply immediately." },
      { title: "Ongoing Support", description: "Check-ins to refine strategies as your child grows." },
    ],
    duration: "45–60 minute sessions, scheduled to suit your family.",
    faqs: [
      { question: "Is this therapy for me or my child?", answer: "It's focused on you as a parent — building your skills, confidence and wellbeing, which in turn benefits your child." },
      { question: "Do both parents need to attend?", answer: "It helps when caregivers align, but sessions can be attended individually or together, whatever suits you." },
      { question: "Can it help with siblings?", answer: "Yes — many strategies support the whole family, including siblings." },
    ],
  },
  {
    slug: "early-intervention",
    title: "Early Intervention",
    shortDescription:
      "Timely, play-based support in the critical early years, when development is most responsive.",
    icon: Sparkles,
    heroTagline: "The earlier the support, the brighter the future.",
    ageRange: "0 – 6 years",
    featured: true,
    overview: [
      "The first six years are the most important window for brain development. Early intervention provides timely, targeted support to children showing developmental concerns, giving them the best possible start.",
      "Our team works through play and everyday routines to build communication, motor, social and thinking skills, while coaching families to support development at home.",
    ],
    symptoms: [
      "Not meeting developmental milestones",
      "Delayed speech or understanding",
      "Limited social interaction or play",
      "Motor or coordination delays",
      "Difficulty with attention",
      "Feeding or sensory concerns",
    ],
    benefits: [
      "Maximised developmental progress",
      "Stronger communication and play",
      "Better motor and thinking skills",
      "Reduced impact of delays",
      "Confident, coached parents",
      "A strong foundation for school",
    ],
    process: [
      { title: "Early Screening", description: "We assess development across all key domains." },
      { title: "Family-Centred Plan", description: "A play-based plan embedded in daily routines." },
      { title: "Therapy & Coaching", description: "Sessions plus parent coaching for everyday learning." },
      { title: "Regular Reviews", description: "Frequent reviews to keep pace with rapid early growth." },
    ],
    duration: "Individualised; frequency reflects your child's needs and goals.",
    faqs: [
      { question: "Why is early intervention so important?", answer: "Young brains are highly adaptable. Support during these years is more effective and can change developmental trajectories." },
      { question: "My child is very young — is it too early?", answer: "It's never too early to support development. Even in infancy, timely help makes a difference." },
      { question: "How involved are parents?", answer: "Central. We coach you to weave developmental support into everyday play and routines." },
    ],
  },
  {
    slug: "group-therapy",
    title: "Group Therapy",
    shortDescription:
      "Small, supportive groups where children practise social, communication and emotional skills together.",
    icon: Users2,
    heroTagline: "Growing together, learning together.",
    ageRange: "3 – 16 years",
    overview: [
      "Group therapy gives children a safe, structured space to practise social and communication skills with peers, guided by our therapists. Real interaction is the best way to build friendship, turn-taking and cooperation skills.",
      "Groups are carefully matched by age and goals, and blend play, activities and gentle coaching to build confidence and social competence.",
    ],
    symptoms: [
      "Difficulty making or keeping friends",
      "Trouble with turn-taking and sharing",
      "Shyness or social anxiety",
      "Difficulty reading social cues",
      "Struggles in group settings",
      "Limited conversation skills",
    ],
    benefits: [
      "Improved social and friendship skills",
      "Better turn-taking and cooperation",
      "Increased confidence with peers",
      "Practice reading social cues",
      "Reduced social anxiety",
      "Fun, motivating peer learning",
    ],
    process: [
      { title: "Assessment & Matching", description: "We match your child to a group by age and social goals." },
      { title: "Group Goals", description: "Shared and individual goals guide each session." },
      { title: "Group Sessions", description: "Structured, playful sessions building real social skills." },
      { title: "Parent Updates", description: "Regular feedback and strategies to reinforce skills." },
    ],
    duration: "45–60 minute weekly sessions, running in term-based blocks.",
    faqs: [
      { question: "How big are the groups?", answer: "Small — typically 3 to 6 children — so every child gets attention and practice." },
      { question: "Can group and individual therapy combine?", answer: "Yes. Many children benefit from both individual sessions and group practice." },
      { question: "How are groups formed?", answer: "By age and shared goals, so children practise with suitable peers." },
    ],
  },
  {
    slug: "tele-therapy",
    title: "Tele Therapy",
    shortDescription:
      "Effective online therapy sessions delivered securely to your home, wherever you are.",
    icon: Video,
    heroTagline: "Expert therapy, from the comfort of home.",
    ageRange: "3 – 16 years",
    overview: [
      "Tele-therapy brings NeuroShine's expert care to your home through secure video sessions. It's ideal for families with travel constraints, busy schedules or who live further away, without compromising on quality.",
      "Our therapists use engaging digital activities and coach parents in real time, making online sessions interactive, effective and convenient.",
    ],
    symptoms: [
      "Difficulty attending in-clinic sessions",
      "Long travel distances",
      "Busy family schedules",
      "Need for flexible timing",
      "Continuity during travel or illness",
      "Preference for home-based support",
    ],
    benefits: [
      "Convenient, flexible scheduling",
      "No travel time or cost",
      "Care in your child's familiar environment",
      "Real-time parent coaching",
      "Continuity of therapy anywhere",
      "The same expert therapists",
    ],
    process: [
      { title: "Online Consultation", description: "An initial video assessment of your child's needs." },
      { title: "Personalised Plan", description: "A tailored plan designed for online delivery." },
      { title: "Live Video Sessions", description: "Interactive sessions with engaging digital activities." },
      { title: "Home Support", description: "Guidance and materials to practise between sessions." },
    ],
    duration: "30–45 minute sessions, scheduled flexibly to suit your family.",
    faqs: [
      { question: "Is online therapy as effective?", answer: "For many children and goals, tele-therapy is highly effective, especially with active parent involvement, which we coach in real time." },
      { question: "What do I need?", answer: "A device with a camera, a stable internet connection and a quiet space. We guide you through the simple setup." },
      { question: "Is it secure and private?", answer: "Yes. Sessions are delivered over secure, private video with confidentiality maintained throughout." },
    ],
  },
  {
    slug: "assessment",
    title: "Assessment Services",
    shortDescription:
      "Comprehensive, standardised evaluations that provide clarity, diagnosis and a clear path forward.",
    icon: ClipboardList,
    heroTagline: "Clarity that guides the right support.",
    ageRange: "0 – 18 years",
    overview: [
      "A thorough assessment is the foundation of effective support. Our psychologists and therapists use standardised, evidence-based tools to understand your child's development, strengths and needs across communication, learning, behaviour and more.",
      "You receive a clear written report with practical recommendations, so you and your child's team know exactly how to move forward with confidence.",
    ],
    symptoms: [
      "Uncertainty about your child's development",
      "Concerns raised at school",
      "Delayed milestones",
      "Learning or behaviour difficulties",
      "Need for a formal diagnosis",
      "Planning the right support",
    ],
    benefits: [
      "A clear understanding of your child",
      "Accurate diagnosis where appropriate",
      "A detailed, practical written report",
      "Tailored recommendations",
      "Documentation for school support",
      "Confidence in the next steps",
    ],
    process: [
      { title: "Intake & History", description: "We gather background information and your concerns." },
      { title: "Standardised Testing", description: "Age-appropriate, evidence-based assessment sessions." },
      { title: "Analysis", description: "Our specialists interpret results carefully." },
      { title: "Feedback & Report", description: "A clear feedback session and detailed written report." },
    ],
    duration: "Usually 1–3 sessions depending on the assessment, plus a feedback meeting.",
    faqs: [
      { question: "How long does it take to get results?", answer: "You'll typically receive your feedback session and written report within one to two weeks of the final assessment session." },
      { question: "Can the report be used at school?", answer: "Yes. Reports include recommendations you can share with your child's school to access support." },
      { question: "Do I need a referral?", answer: "No referral is needed — you can book an assessment directly with us." },
    ],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getAllServiceSlugs(): string[] {
  return services.map((s) => s.slug);
}

export const featuredServices = services.filter((s) => s.featured);
